### PR TITLE
Migration to donet 8

### PR DESCRIPTION
**Pull request by z3rone**
Mono is depcreated. By now Microsoft offers an installation option for dotnet on Linux (see https://dotnet.microsoft.com/en-us/download/dotnet/8.0). I've updated the DLLs with the latest dotnet 8 compatible versions from https://github.com/thermofisherlsms/RawFileReader. As there are no tests the only thing I can say is, that it seems to work now with our software. Maybe someone else can test further.

As this is not backwards compatible with mono this should be a new major version of the package.

### CODE REVIEW

**Comment by dowerner** [comment]
Thank you for opening this PR. As you pointed out, these changes might break compatibility on some systems, therefore I cannot just merge your PR. You further point out that there are no integration- / regression-tests to ensure that no features break through the changes you made. I will try to remedy this before we move forward.
Thank you also for sharing the source where you got the DLLs from. There have been quite a few supply chain attacks on open source projects so PRs containing build artefacts raise suspicion. I may have to verify with the authors if our license is still applicable for the new versions (it seems to be).

Would you be available for questions or to run tests?

**Comment by z3rone** [comment]
Thank you for your comment. I understand the worries about the binaries. Feel free to compare hashes with the thermo repo. I am happy to assist the migration but so far I've only took a slight glance at the actual code of this project.

Regarding breaking changes we might be able to implement conditional loading of the correct dll depending on the dotnet version of the environment:

```
>>> import pythonnet
>>> pythonnet.load('coreclr')
>>> from System import Environment
>>> Environment.Version.get_Major()
8
```

I'll try to implement something

**Comment by dowerner** [comment]
I had something similar in mind for the compatibility. Since your PR I have created a new [milestone](https://github.com/ethz-institute-of-microbiology/fisher_py/milestone/1) for version 2 of this library. Currently, I am writing tests to ensure that we catch regression that may be introduced when we do all the updates.

**Comment by z3rone** [comment]
I've updated the code to detect the installed dotnet version and load the DLLs based on that. Also the DDLs are now linked from a submodule. I've done manual testing for mono, dotnet5-sdk and dotnet8-sdk. For the first two I used docker images mono:latest and bitnami/dotnet-sdk:5. For dotnet8 the bitnami/dotnet-sdk:8 did not work but [downloading it from Microsoft](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.404-macos-x64-installer) into a debian:latest container worked.

Does the ethz-institute-of-microbiology org support github actions? It might be a good opportunity to implement automatic testing.

**Comment by dowerner** [comment]
Thank you for all your efforts!
We use GitHub actions for building and publishing but I will add a test stage as well for v2. As soon as the tests are present I would suggest that you rebase your branch on the v2_0_0 branch that I created last week.

**Comment by dowerner** [comment]
Can you change the target branch to **v_2_0_0**?

**Comment by z3rone** [comment]
sure

**Comment by dowerner** [comment]
I have pushed the tests to **v_2_0_0**. As soon as you merge the tests back, we can check if they work for your various Docker environments.

**Comment by z3rone** [comment]
I merged the tests and sucessfully ran them in docker `bitnami/dotnet-sdk:5`:
```
(venv) root@c3795b20a784:~/fisher_py# pytest tests/
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.9.2, pytest-8.3.4, pluggy-1.5.0
rootdir: /app/fisher_py
configfile: pyproject.toml
collected 46 items

tests/net_wrapping/test_wrapped_arrays.py .........                                                                                                                                                  [ 19%]
tests/net_wrapping/test_wrapped_lists.py .........                                                                                                                                                   [ 39%]
tests/raw_file_reader/test_raw_file_access.py ............                                                                                                                                           [ 65%]
tests/raw_file_reader/test_raw_file_reader_adapter.py .                                                                                                                                              [ 67%]
tests/test_raw_file.py ...............                                                                                                                                                               [100%]

============================================================================================ 46 passed in 9.18s ============================================================================================
```

**Comment by z3rone** [comment]
Here my command to reproduce:
```
docker run -v $(pwd):/app/fisher_py \
    -it --rm  \
    bitnami/dotnet-sdk:5 \
    bash -c "apt update && \
             apt install -y python3 python3-pip python3-venv && \
             python3 -m venv venv && \
             source venv/bin/activate && \
             pip install requests pytest && \
             pip install /app/fisher_py/ && \
             cd /app/fisher_py/ && \
             pytest tests/"
```

**Comment by z3rone** [comment]
I am currently trying to get it working fot dotnet8 but have some issues even with the latest version from the Microsoft website:
```
E   System.IO.FileLoadException: Could not load file or assembly 'ThermoFisher.CommonCore.RawFileReader, Version=8.0.6.0, Culture=neutral, PublicKeyToken=1aef06afb5abd953'.
E      at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
E      at System.Reflection.Assembly.LoadFrom(String assemblyFile)
E      at Python.Runtime.AssemblyManager.LoadAssemblyFullPath(String name) in /home/benedikt/.cache/uv/sdists-v6/.tmpkW03e6/pythonnet-3.0.5/src/runtime/AssemblyManager.cs:line 259
E      at Python.Runtime.CLRModule.AddReference(String name) in /home/benedikt/.cache/uv/sdists-v6/.tmpkW03e6/pythonnet-3.0.5/src/runtime/Types/ClrModule.cs:line 113
E      at InvokeStub_CLRModule.AddReference(Object, Span`1)
E      at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by z3rone** [comment]
okay it was a problem with docker on Mac M1. No problem with this command on a Linux x64 host:
```
docker run -v $(pwd):/app/fisher_py \
    -it --rm  \
    python:3.10 \
    bash -c "apt update && \
             apt install -y wget && \
             mkdir -p /opt/dotnet8 && \
             cd /opt/dotnet8 && \
             wget -O dotnet.tar.gz https://download.visualstudio.microsoft.com/download/pr/4e3b04aa-c015-4e06-a42e-05f9f3c54ed2/74d1bb68e330eea13ecfc47f7cf9aeb7/dotnet-sdk-8.0.404-linux-x64.tar.gz && \
             tar -xf dotnet.tar.gz && \
             export DOTNET_ROOT=/opt/dotnet8 && \
             export PATH=$PATH:$DOTNET_ROOT && \
             python -m venv venv && \
             source venv/bin/activate && \
             pip install requests pytest && \
             pip install /app/fisher_py/ && \
             cd /app/fisher_py/ && \
             pytest tests/"
```

**Comment by z3rone** [comment]
...and finally a working command for testing mono:
```
docker run -v $(pwd):/app/fisher_py \
    -it --rm \
    python:3.9-bookworm \
    bash -c "apt update && \
             apt install -y mono-complete && \
             python -m venv venv && \
             source venv/bin/activate && \
             pip install requests pytest && \
             pip install /app/fisher_py/ && \
             cd /app/fisher_py/ && \
             pytest tests/"
```

**Comment by z3rone** [comment]
turns out simply using `bitnami/dotnet-sdk:8` also works for dotnet8-sdk testing if the docker host is x64 linux

**Comment by dowerner** [comment]
Amazing, thank you a lot for your testing efforts! I will also run the tests with your instructions and then we can probably close the PR soon.

**Comment by dowerner** [comment]
I tried to validate the DLLs that you put into the project but I got different checksums. When I compared the file sizes it seems that your versions are all a lot smaller than the once from the source repository:
image

Did you recompile them with different settings?

**Comment by z3rone** [comment]
I did not compile these files but symlinked them into the thermo submodule to the original DLLs:
```
ls -l src/fisher_py/dll/net8
lrwxr-xr-x  1 user  users  100 29 Dec 12:21 OpenMcdf.Extensions.dll -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/OpenMcdf.Extensions.dll
lrwxr-xr-x  1 user  users   89 29 Dec 12:21 OpenMcdf.dll -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/OpenMcdf.dll
lrwxr-xr-x  1 user  users  126 29 Dec 12:21 ThermoFisher.CommonCore.BackgroundSubtraction.dll -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/ThermoFisher.CommonCore.BackgroundSubtraction.dll
lrwxr-xr-x  1 user  users  126 29 Dec 12:21 ThermoFisher.CommonCore.BackgroundSubtraction.xml -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/ThermoFisher.CommonCore.BackgroundSubtraction.xml
lrwxr-xr-x  1 user  users  109 29 Dec 12:21 ThermoFisher.CommonCore.Data.dll -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/ThermoFisher.CommonCore.Data.dll
lrwxr-xr-x  1 user  users  109 29 Dec 12:21 ThermoFisher.CommonCore.Data.xml -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/ThermoFisher.CommonCore.Data.xml
lrwxr-xr-x  1 user  users  127 29 Dec 12:21 ThermoFisher.CommonCore.MassPrecisionEstimator.dll -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/ThermoFisher.CommonCore.MassPrecisionEstimator.dll
lrwxr-xr-x  1 user  users  127 29 Dec 12:21 ThermoFisher.CommonCore.MassPrecisionEstimator.xml -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/ThermoFisher.CommonCore.MassPrecisionEstimator.xml
lrwxr-xr-x  1 user  users  118 29 Dec 12:21 ThermoFisher.CommonCore.RawFileReader.dll -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/ThermoFisher.CommonCore.RawFileReader.dll
lrwxr-xr-x  1 user  users  118 29 Dec 12:21 ThermoFisher.CommonCore.RawFileReader.xml -> ../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/ThermoFisher.CommonCore.RawFileReader.xml
```

 I don't know how python handles this in Windows but in Linux it just resolves the link to it's target when builing the package.

**Comment by z3rone** [comment]
I guess the file's content under windows ist just the text referring to the target like `../../../../libs/thermofisherlsms_RawFileReader/Libs/NetCore/Net8/Assemblies/ThermoFisher.CommonCore.RawFileReader.dll`

**Comment by z3rone** [comment]
A quick google search suggests that you need to enable linking in git https://superuser.com/questions/1713099/symbolic-link-does-not-work-in-git-over-windows

**Comment by dowerner** [comment]
Okay, I see. I was wondering about that other folder. In that case I would ask you to replace the links with the actual assemblies since otherwise hatchling will not generate a functional package during build. Btw. I asked the maintainer of the RawFileReader if we are allowed to use all versions of the DLLs to distribute with this package and he said the license is still valid. So there should be no issue with adding the assemblies directly.

**Comment by z3rone** [comment]
Are you sure about the hatchling problem? When I build the image (either with the build mobule or with hatch) the actual DLL files are included in the whl file in place of the symlinks. I have no strong objections to copying the actual DLLs into this project but I thought this way is a bit cleaner as no manual hash comparison would be necessary and updating could be done by simply pulling the latest version of the submodule.

**Comment by dowerner** [comment]
I guess it comes down to the OS being used for the build. On Windows I get the small symlink files and if I do the same thing on WSL the symlinks are replaced by the DLL files.
While I agree with your goal of making it easier to update I would prefer to add the versions explicitly and keep the build working on all platforms. Especially bad is that on Windows you do not immediately realize the problem and I want to keep the repository as accessible as possible. I also did not have great experiences with sub-repositories in the past so I would rather have this be separate. An alternative could be a script that downloads the most recent versions from the source repository and updates the DLLs.

What are your thoughts on this? Would the option of a script that we put into `/root/utils/update_dotnet_assemblies_from_source.py` be a viable option? I can write such a script and commit it to your branch if you want.

**Comment by z3rone** [comment]
Have you tried the `core.symlinks` git option on Windows? If that works, a "contribution" or "installing from source" section in the readme would be the preferred option to me. As far as I understand it the following sould pull the repo in such a way, that also Windows can build the package:
```
git clone -c core.symlinks=true <repo>
cd <repo>
git config core.symlinks true
git submodule update
```

This solution, as well as a download script, would require the user to read the documentation. My personal preference (assuming this does in fact works for Windows) would then be the linking option. If this option is not accessable enough I would suggest we stick to adding the DLLs by hand.

**Comment by z3rone** [comment]
let's just stick to manual adding I guess. I'll push an according commit in a sec

**Comment by dowerner** [comment]
Believe me I sympathize with the goal to make the process of updating the DLLs more automated. But since it requires additional steps to make the repo work on all platforms I really want to make this an explicit step.
Also this is not something I would want to do very frequently since there may be breaking changes in the API that requires parts of the wrappers to be rewritten. As far as I know, only the newest DLLs are available on the sub repository so if there would be breaking changes we could get into the situation where you need to find a specific commit for the submodule to make the project run again.

**Comment by dowerner** [comment]
> let's just stick to manual adding I guess. I'll push an according commit in a sec

Thank you

**Comment by dowerner** [comment]
I validated all checksums against the newest version of the source repo and also ran all the tests via Docker. Additionally, I removed the `root/fisher_py` folder where the DLLs where also present.

If the state is fine for you I would go ahead and merge to `v_2_0_0`. After that I will try to get the GitHub actions running on that branch to see if the tests work in the pipeline.

**Comment by z3rone** [comment]
sounds all fine to me 👍

**Pull request merged**
