### PR TITLE
Added raw file reader factory and thread accessor

### PR DESCRIPTION
**Pull request by dowerner**
This feature branch adds wrappers for the **RawFileReaderFactory** and the **RawFileThreadAccessor** classes.

### CODE REVIEW

**Review by keesh0 — APPROVED** [review]

**Comment by keesh0** [comment]
Thanks, approved.  
I will test on both Windows 11 and Linux (Centos).
Will there be a new version of fisher_py or is there another easy way that I can pull down this change?
thxn e.-

**Comment by dowerner** [comment]
Since this has yet to be tested, I would suggest you build the package yourself:
- Clone the repository and checkout the branch
- Install the **wheel** package in the python environment you are planning to use to build the package
- Run the following command ```python setup.py bdist_wheel```. This will create the file **dist/fisher_py-0.0.1.dev1-py3-none-any.whl**
- Use ```pip install fisher_py-0.0.1.dev1-py3-none-any.whl``` to install the package. I would suggest to use a Python venv so you don't have to uninstall fisher_py from your regular environment (never mind if you already use venvs for all your projects ^^)

I hope these instructions are helpful. Let me know if you run into problems.

**Comment by keesh0** [comment]
Sigh.
Cannot open the same raw file in different threads.
Cannot pass IRawDataExtended or IRawFileThreadManager to different threads.
TypeError: cannot pickle 'IRawDataExtended' object
TypeError: cannot pickle 'IRawFileThreadManager' object


Things work much better in C#.
Parallel.ForEach(SteppedIntegerList(firstScanNumber, lastScanNumber+1, stepScanNumber), options, scan_num =>
                {
                    IRawDataPlus rawFileMT = myThreadManager.CreateThreadAccessor();
                    IFileError fileErrorMT = rawFileMT.FileError;
                    extractPerSpectrumDataTask(rawFileMT, scan_num, stepScanNumber, totalNumScans,
                        spectra_base_filename, rtc_base_filename, chroma_data_base_filename, raw_base_dir, firstSpectrum);
                });
                
static void extractPerSpectrumDataTask(IRawDataPlus rawFile, int first_scan_number, int step_scan_num, int total_num_scans,
            string spectra_base_filename, string rtc_base_filename, string chroma_data_base_filename, string raw_base_dir, bool firstSpectrum)
        {
        rawFile.SelectInstrument(Device.MS, 1);
        }

**Comment by dowerner** [comment]
I guess you are trying to use multiple processes, not threads (hence why the objects need to be pickled to be handed to another python instance). In C# you can use multithreading since it can actually utilize multiple cores.

Have you tried creating the thread manager inside the method you use ```p.map()``` on? If this does not work as well on Linux, I would suggest that you run the expensive operation in a C# program that you invoke from your python code. The C# program can then export the relevant data to a file so you are able to process it in python. There are libraries that allow you to save directly to an **.npy** file (e.g. https://github.com/matajoh/libnpy)

**Comment by keesh0** [comment]
Creating the thread manager inside...
worked fine on Windows.
But, Linux fails as usual:
Assertion at mono-threads.c:500, condition `result' not met

Back to C# for some of the work, then return to Python to concatenate the C# threads' work.

**Comment by dowerner** [comment]
I'm sorry to hear this. I can understand your frustration.

Should we still include the changes into the main?

**Comment by keesh0** [comment]
I am not sure.
Maybe somebody can use a good Python paradigm and get them to work?

**Comment by dowerner** [comment]
Potentially, if the bottleneck is IO rather than the CPU. I will merge the PR and see if any new issues pop up.

Good luck with your analysis!

**Comment by keesh0** [comment]
thx

**Pull request merged**
